name: RDP Tunnel Free Access
on: 
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  rdp-setup:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Enable RDP and Bypass Restrictions
      run: |
        # Enable RDP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        
        # Bypass connection limits
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "MaxInstanceCount" -Value 999
        
        # Configure firewall
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        netsh advfirewall firewall add rule name="RDP-Custom" dir=in action=allow protocol=TCP localport=3389
        
    - name: Create User Account
      run: |
        $password = ConvertTo-SecureString "Password123!" -AsPlainText -Force
        New-LocalUser -Name "RDPUser" -Password $password -FullName "RDP User"
        Add-LocalGroupMember -Group "Administrators" -Member "RDPUser"
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDPUser"
        
    - name: Install Cloudflared Tunnel
      run: |
        Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile "cloudflared.exe"
        
    - name: Start RDP Tunnel
      run: |
        # Start Cloudflared in background
        Start-Process -FilePath ".\cloudflared.exe" -ArgumentList "tunnel --url rdp://localhost:3389" -WindowStyle Hidden
        
        # Wait for tunnel to initialize
        Start-Sleep -Seconds 30
        
    - name: Display Connection Info
      run: |
        Write-Output "=== RDP TUNNEL READY ==="
        Write-Output "Username: RDPUser"
        Write-Output "Password: Password123!"
        Write-Output "Port: 3389"
        Write-Output "Tunnel: Cloudflared (check logs for URL)"
        Write-Output "Workflow will run for 1 hour..."
        
    - name: Keep Alive
      run: |
        Start-Sleep -Seconds 3600
